name: Build Apk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 🔄 دریافت کد از مخزن
      - uses: actions/checkout@v3

      # ☕ نصب JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      # 🛠 نصب Android NDK
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r28c

      # 🔧 قابل اجرا کردن فایل gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # ⚡ ساخت فایل APK
      - name: Build APK with Gradle
        run: ./gradlew clean assembleRelease

      # 📦 آپلود خروجی
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: engine.apk
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 90
